version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-attendance-db
    environment:
      MYSQL_ROOT_PASSWORD: "YES"
      MYSQL_DATABASE: AttendanceApp
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: